repos:
      - repo: https://github.com/ambv/black
        rev: stable
        hooks:
              - id: black
                language_version: python3.8
      - repo: git://github.com/pre-commit/pre-commit-hooks
        sha: v1.1.1
        hooks:
              - id: flake8
                additional_dependencies: [flake8-docstrings]
      - repo: https://github.com/asottile/seed-isort-config
        rev: v1.2.0
        hooks:
              - id: seed-isort-config
      - repo: https://github.com/pre-commit/mirrors-isort
        rev: master
        hooks:
              - id: isort
